### ISSUE TITLE
Nombre de las vistas

### ISSUE THREAD

**Issue by LuiosDyet** [1022FSNSANCN02ARED/grupo-05#1]
Agreguen nombre a las vistas. Les va a ayudar después para que estén en sintonía con los nombres de archivos. Como sugerencia nombrarlas (así como los archivos) en snake_case

**Comment by lautarosaya** [comment]
Las tenemos linkeadas en el trello con los nombres de las vistas, nomas que en el pdf no aparecen.

Wireframe Tablet/Laptop/Pc
https://wireframe.cc/pro/pp/2ea131369609969

Wireframe Mobile
https://wireframe.cc/pro/pp/a16706e71614157

Esta bien si las tenemos así?
