### ISSUE TITLE
Render de vista

### ISSUE THREAD

**Issue by LuiosDyet** [1022FSNSANCN02ARED/grupo-05#11]
https://github.com/1022FSNSANCN02ARED/grupo-05/blob/2a4df2d346978387321e6c6e1e63890262ec211d/src/controllers/main-controllers.js#L5

-	Un par de aclaraciones con esta línea.
o	En verdad lo que quieren hacer es renderizar, o sea que es res.render('index');
o	De la misma manera no es necesaria la ruta porque aclararon la ruta base de todas las views en app.js en app.set("views", path.join(__dirname, "./views"));
o	No es necesario aclarar que es ejs, ya lo aclararon en app.js con app.set("view engine", "ejs");

**Comment by lautarosaya** [comment]
ya esta solucionado
