### ISSUE TITLE
Colores del sitio

### ISSUE THREAD

**Issue by LuiosDyet** [1022FSNSANCN02ARED/grupo-05#3]
El logo es muy bueno, extraigan los colores y ya tengalos guardados como colores del sitio para darle más coherencia al mismo

**Comment by lautarosaya** [comment]
Dale, eso vamos a hacer. Gracias ;)

**Comment by atarico** [comment]
Hola Luis, en la carpeta scss agregué un archivo (_style_root.scss) con los colores que vamos a usar
