### ISSUE TITLE
Falta vista de carrito

### ISSUE THREAD

**Issue by Piarrot** [1022FSNSANCN02ARED/grupo-05#4]
Les estaria faltando la vista del carrito, revisé hasta el ultimo commit antes del sprint y no estaba. 

En la ultima version hay una ruta hacia la vista del carrito, pero no existe el archivo. https://github.com/1022FSNSANCN02ARED/grupo-05/blob/5e00b4398f0acd6a196b4e8290d632fc145be858/src/controllers/cart-controllers.js#L6

**Comment by lautarosaya** [comment]
Hola Pablo, estamos ayudando a hacer el carrito porque el que estaba designado a hacerlo tuvo unos problemas (fuera del curso). Ya para esta semana la tenemos subida al repo.

**Comment by atarico** [comment]
Estamos viendo si pódemos rescatar el trabajo que se haya hecho y en caso de que sea imposible, ya varios de nosotros estamos trabajando en un carrito por su cuenta, la idea es presentarlos y que se use el que la mayoría vote.

**Comment by atarico** [comment]
Hoy recién pude terminar de subir el carrito que quedamos debiendo del sprint pasado. Me falta todavía darle la funcionalidad a los diferentes botones y que sume todo pero la vista sería algo así:

![Captura de pantalla_20230118_131418](https://user-images.githubusercontent.com/99090116/213231736-8d3f5047-d56a-4eab-af10-7fff1e5b0dd8.png)
