### ISSUE TITLE
Retro

### ISSUE THREAD

**Issue by Piarrot** [1022FSNSANCN02ARED/grupo-05#5]
https://github.com/1022FSNSANCN02ARED/grupo-05/blob/5e00b4398f0acd6a196b4e8290d632fc145be858/RETRO.md

Viendo el jamboard de la retro... 

- [Empezar a hacer] "Reuniones diaras y semanales con horario FIJO"
- [Dejar de hacer] "PROCASTINAR - posponer el trabajo"
- [Mas de] "Todos los dias dediclare por lo menos 1hs"
- [Mas de] "Revisar el trello"

¿qué accionables sacaron de estos puntos? ¿qué resolvieron sobre estos temas?

**Comment by atarico** [comment]
Ésta semana nos estuvimos reuniendo todos los días a las 11am y nos planteábamos objetivos diarios que pudiéramos completar. Al principio costó pero de a poco la mayoría estamos en mejor ritmo o por lo menos esa es mi sensación. Que el resto exponga su idea pero creo que estamos cumpliendo de a poco las consignas de la RETRO, mejor que el sprint pasado estamos!!!

**Comment by fedegaay** [comment]
Buenos dias, si tuvimos una mejora considerable con las reuniones y la organizacion del grupo, tambien tuvimos unas bajas parciales por problemas de salud y personales que no nos permitian estar al 100% dedicados al grupo, ya todo se normalizo y ahora tiramos para el mismo lado todos juntos. Gracias por las Issues. Saludos
