### ISSUE TITLE
`__dirname + res.sendFile` ??

### ISSUE THREAD

**Issue by Piarrot** [1022FSNSANCN02ARED/grupo-05#6]
https://github.com/1022FSNSANCN02ARED/grupo-05/blob/2b0dcea777dd19e33ba9750c87018089cb95d099/src/controllers/main-controllers.js#L4-L11

¿Cuál es la idea con esto de arrancar la linea con `__dirname`? Todos los controladores están igual... ojo con eso

**Comment by atarico** [comment]
Eso fue un error que tuve armando la primera ruta. El " __dirname + ruta " estaba como comentario y cuando lo borré no me dí cuenta que quedó y al copiar y pegar las demás rutas no me percaté que tenía ese error. 
El código ya fue corregido. Gracias!!!
![Captura de pantalla_20230113_181654](https://user-images.githubusercontent.com/99090116/212420797-af36aedf-dbe1-439b-8dcf-99137f29ec0a.png)
