### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Piarrot** [1022FSNSANCN02ARED/grupo-05#7]
Ojo con este "footer"

https://github.com/1022FSNSANCN02ARED/grupo-05/blob/5e00b4398f0acd6a196b4e8290d632fc145be858/src/views/index.html#L245-L283

Está... como raro. Copiado casi literal de mercadoliebre, y no encaja con el resto del sitio (en cuanto a estructura). Está como "revoleado ahi". No entiendo cómo quedó asi, tal vez un conflicto mal resuelto o commitearon algo que no estaba terminado.

Les sugiero que lo limpien, y tengan en cuenta que el footer del wireframe es bastante diferente a esto. ¿eso fue un cambio apropósito?

**Comment by atarico** [comment]
Si, tuvimos un mal entendido pero el nuevo footer podría ser algo como la foto que se adjunta pero no está 100% definido (está en proceso todavía). Si la mayoría de miembros les parece bien, usamos éste.
![Captura de pantalla_20230113_183605](https://user-images.githubusercontent.com/99090116/212423798-b109214e-b17d-4d45-94c1-c1fa66247419.png)

**Comment by fedegaay** [comment]
Buenos dias, si tuvimos un mal entendido con el footer, ese que subio mi compañero arriba va a ser (casi definitivo) el footer de la pagina. Saludos
