### ISSUE TITLE
Sass

### ISSUE THREAD

**Issue by Piarrot** [1022FSNSANCN02ARED/grupo-05#8]
Por los commits veo que no todos están usando Sass.

Yo les habia permitido usar Sass, con la condición de que todo el equipo estuviera de acuerdo y los que supieran usarlo le enseñaran al resto. 

Si no todos entienden o quieren aprender cómo trabajar con scss (lo cuál es entendible porque ya están aprendiendo un montón de cosas además), les voy a pedir que trabajen directamente con CSS.

**Comment by lautarosaya** [comment]
Hola pablo, es algo que estuvimos hablando estos dias. Quedamos con que ibamos a empezar a usarlo todos, y que si se les complica mucho a los demas lo dejamos de lado y usabamos css.
